### ISSUE TITLE
Could not load 'plugins/ServerRegionProtect-0.6.0.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bstats/bukkit/Metrics$CustomChart

### ISSUE THREAD

**Issue by pavog** [RitaSister/WorldGuardRegionProtect#17]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

On a fresh server installation, I installed WorldEdit (7.2.10), WorldGuard (7.0.7) and WorldGuardRegionProtect from dev.bukkit.org ([ServerRegionProtect-0.6.0](https://dev.bukkit.org/projects/worldguardregionprotect/files/3380342)).

On server startup I get this error:

```
[10:49:07] [Server thread/ERROR]: Could not load 'plugins/ServerRegionProtect-0.6.0.jar' in folder 'plugins'
15 | org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bstats/bukkit/Metrics$CustomChart
```

### To Reproduce

1. Download the plugins I mentioned above
2. Start your server

### Expected behaviour

Should not throw this exception.

### Error log (if applicable)

https://mclo.gs/mrB4EAF

### WorldGuardRegionProtect version

0.6.0

### Checklist

- [X] I am using the newest build from https://ci.codemc.io/job/RitaSister/job/WorldGuardRegionProtect/ and the issue still persists.

### Anything else?

No, I did not use this dev build from your CI.
I used the latest file from dev.bukkit.org.

**Comment by RitaSister** [comment]
Just use last version of plugin WorldGuardRegionProtect 0.7.1-pre9 for lasted server version.

**Comment by pavog** [comment]
Can you please upload the newer versions to dev.bukkit.org, too?

**Comment by RitaSister** [comment]
Because plugin ServerRegionProtect-0.6.0 is the old versions and cannot to support for it.

**Comment by RitaSister** [comment]
> Can you please upload the newer versions to dev.bukkit.org, too?

you can download last versions from here https://ci.codemc.io/job/RitaSister/job/WorldGuardRegionProtect/

**Comment by pavog** [comment]
Okay, so you won't update the project on dev.bukkit.org anymore?

**Comment by RitaSister** [comment]
I updated on dev.bukkit.org to 0.7.1-pre9

> Okay, so you won't update the project on dev.bukkit.org anymore?

Plugin has been renamed and 'ServerRegionProtect' is the oldest name. 
Just need a new link: https://dev.bukkit.org/projects/worldguardregionprotect/

**Comment by RitaSister** [comment]
So your problem are fixed?

**Comment by pavog** [comment]
Yes thank you.
