### ISSUE TITLE
Give creative upon entering a region

### ISSUE THREAD

**Issue by dkhawser** [RitaSister/WorldGuardRegionProtect#8]
### What feature do you want to see added?

I would like to know if there is a way to setup a region so that when players with certain permissions enter that region, they would be given Creative gamemode, and then upon leaving, it would be taken away.

### Are there any alternatives?

I have not tried anything else, I'm not sure if this is even possible, I just wanted to ask if you knew of a way that it could be done.

### Anything else?

The reason I wanted to be able to do this, is so that I could give my server staff temporary access to creative when doing builds for the server, rather than their own personal builds.

**Comment by RitaSister** [comment]
WorldGuard have a flag like "game-mode". So u need set "creative" or else gamemode which you need.

**Comment by RitaSister** [comment]
And you can give permissions for access to region.

**Comment by RitaSister** [comment]
permissions for access to protected region: wgrp.regionprotect
